production:
  adapter: postgresql
  encoding: unicode
  database: rybu
  pool: 5
  username: rybu
  password: 123123
  host: 127.0.0.1
development:
  adapter: postgresql
  encoding: unicode
  database: rybu
  pool: 5
  username: rybu
  password: 123123
  host: 127.0.0.1
test:
  adapter: postgresql
  encoding: unicode
  database: rybu
  pool: 5
  username: rybu
  password: 123123
  host: 127.0.0.1